import '../styles/globals.css'
import Head from 'next/head'
import type { AppProps } from 'next/app'
import { Provider } from 'react-redux'
import { createStore } from '../redux/store'
import { Layout } from 'antd'
import Toast from '../components/Toast'

const { Header, Content, Footer } = Layout;

let store = createStore()

export default function App({ Component, pageProps }: AppProps) {
  return <Provider store={store}>
    <script
      src="https://accounts.google.com/gsi/client"
      async
      defer
    ></script>
    <Head>
      <title>Truong Dinh Duc</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
      <Content >
        <Component {...pageProps} />
      </Content>
    </Layout>
    <Toast />
  </Provider>
}
